### ISSUE TITLE
Create Separate Project Branch for Server

### ISSUE THREAD

**Issue by anushkajp** [anushkajp/Team6_OnlineTutoringApplication#20]
As a developer, I want to have the server branch separate from the client side for ease of development in the same repository.
Acceptance criteria:

- [x]  basic express js created in server branch
- [x]  repository cloned
- [x]  server branch has main, release, and develop branches

**Comment by diananle** [comment]
main, develop, and release branch created for server
![image](https://github.com/anushkajp/Team6_OnlineTutoringApplication/assets/96149964/d03202cf-1012-4e5e-b785-db4a598695af)

**Comment by diananle** [comment]
Basic file structure created in server folder
![image](https://github.com/anushkajp/Team6_OnlineTutoringApplication/assets/96149964/10260769-d9d3-4e3c-a0f2-297ecb500021)
