### ISSUE TITLE
review service

### ISSUE THREAD

**Issue by diananle** [anushkajp/Team6_OnlineTutoringApplication#71]
- [x] create all endpoints with proper HTTP status codes and business logic
- [x] post
- [x] patch
- [x] delete
- [x] get all 
- [x] get one
- [x] No dupicates - one review between student and tutor 
- [x] Check if only students can make reviews
- [x] Minimum rating of 1 and maximum rating of 5 logic add
- [ ] Find the avg tutor rating

**Comment by apoorva-chitti** [comment]
Base code is done, testing needs to be done.

**Comment by apoorva-chitti** [comment]
Tried testing, and I think there is routing.

**Comment by apoorva-chitti** [comment]
Code written for review service.
[reviewService.txt](https://github.com/anushkajp/Team6_OnlineTutoringApplication/files/13261941/reviewService.txt)

**Comment by mahimahithefish** [comment]
Patch bug needs to be fixed and calculating average tutor. All other logic implementations and logic done

**Comment by apoorva-chitti** [comment]
average tutor fixed client side - apoorva
